# ---------------------------------------------------> zizmor.toml <---------------------------------------------------
# zizmor - A static analysis tool for GitHub Actions.
# https://docs.zizmor.sh/configuration


rules:
  template-injection:
    disable: false
  unpinned-uses:
    disable: false
  use-trusted-publishing:
    disable: false
