name: Latest Changes

on:
  pull_request_target:
    branches:
      - main
    types:
      - closed

jobs:
  latest-changes:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: tiangolo/latest-changes@0.4.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          latest_changes_file: CHANGELOG.md
          latest_changes_header: "## Latest Changes"
