# .github/workflows/publish-on-tag.yml
name: Publish Python Package with uv

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'  # Triggers on tags like v1.0.0

jobs:
  publish:
    name: Build and Publish with uv
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up uv
        uses: astral-sh/setup-uv@eb1897b8dc4b5d5bfe39a428a8f2304605e0983c # v7

      - name: Build with uv
        run: uv build

      - name: Publish with uv
        env:
          UV_PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: uv publish --token $UV_PYPI_TOKEN

      - name: Run latest-tag
        uses: EndBug/latest-tag@latest
        with:
          # You can change the name of the tag or branch with this input.
          # Default: 'latest'
          ref: latest
          # If a description is provided, the action will use it to create an annotated tag. If none is given, the action will create a lightweight tag.
          # Default: ''
          description: The latest release.
          # Force-update a branch instead of using a tag.
          # Default: false
          force-branch: false
          # Directory to use when executing git commands
          # Default: '${{ github.workspace }}'
          git-directory: '${{ github.workspace }}'
